### ISSUE TITLE
Odd urls when SEO url options are on

### ISSUE THREAD

**Issue by iandberg** [lightspeedretail/webstore#650] opened 2015-04-03 17:29 UTC
admin > SEO > URL
When both options are on, the product url seems odd. e.g.:
http://www.missionarymall.com/store/http%3A-wwwmissionarymallorg-store-elders-suits-99-suits-%2499-black-suit-%2499-black-suit/dp/1018
Is this what the url is supposed to look like? We noticed this around 3.1.7 or so.
![seo_options](https://cloud.githubusercontent.com/assets/583913/6985840/611d6844-d9ec-11e4-938f-2f88c8f4341d.png)

Thanks!

**Comment by gabeguz** [comment] 2015-04-03 17:40
That's currently being addressed, and should be fixed in 3.2.6 -- I'm going to close this as a duplicate of:  

https://github.com/lightspeedretail/webstore/issues/630

Thanks for the report.

**Closed by gabeguz** 2015-04-03 17:40 UTC

**Comment by gabeguz** [comment] 2015-04-16 15:02
This has been fixed, however you may need to toggle the "Use product categories in product urls" and/or the "use product codes in product urls" for the fix to take effect, as the urls in the db need to be re-generated.
