### ISSUE TITLE
Issues with $this->CanonicalUrl Populating Correctly in controllers/SearchController.php?

### ISSUE THREAD

**Issue by supert3d** [lightspeedretail/webstore#569] opened 2013-10-29 17:18 UTC
Most of the other views seem OK. Just when selecting brands/designers. $this->CanonicalUrl appears to be malformed. 

View (HTML) Source: 
[code]
&lt;link rel="canonical" href="http://shop.wheninroam.com/http://shop.wheninroam.com/brand/213-industry"/&gt;
[/code]

**Comment by gabeguz** [comment] 2015-02-18 02:58
Closing as duplicate of #630

**Closed by gabeguz** 2015-02-18 02:58 UTC
