### ISSUE TITLE
Canonical URL Issue

### ISSUE THREAD

**Issue by n-ck** [lightspeedretail/webstore#630] opened 2014-09-04 19:50 UTC
The Canonical URL's seem messed up on our Web Store since one of the last updates. This leads to a huge SEO issue.

The canonical URL shows: domain/canonical url in stead of just the canonical url.

Can someone from programming please look into this and provide a fix that I can manually upload to our servers?

Thank you very much!

**Comment by n-ck** [comment] 2014-10-03 15:52
Okay thanks, we don't have that setting enabled at the moment and the canonical URL's are still not displaying correctly.

I fixed it (temporarily) this way in the view _head.php file. I have to say that this is a major SEO issue for Lightspeed web stores (especially for larger content web stores like the store I'm working for). A lot of store owners don't have the technical knowledge to notice this bug and the probably to see their rankings dropping in Google while they are paying a SEO company top-dollar...

**Comment by gabeguz** [comment] 2015-02-18 02:59
For more details, see also #569

**Comment by peteles** [comment] 2015-03-29 03:47
Hello, I opened a ticket on august 2014 about this problem and LightSpeed still has not solved it. What is taking so long? I don't understand.

This is a major problem for us by preventing to do SEO on our site. Please, it would it appreciated to have this problem solved.

Please see Support Request #00183010

**Comment by gabeguz** [comment] 2015-03-30 00:25
This issue is currently being worked on.

**Comment by n-ck** [comment] 2015-03-30 14:09
Hi Peteles,

Unfortunately Lightspeed takes forever to fix important SEO bugs like this, they don't prioritize issues that really matter in their bug/programming backlog and it's very frustrating for webstore owners that try to keep up with the competition! 

I have fixed this issue manually though and can help you out if you're interested. Let me know!

Thanks, Nick

**Comment by peteles** [comment] 2015-04-01 01:32
Hello n-ck,

Thanks for your offer, yes I'm interested. I think you could share also with LightSpeed, may be it will accelarate the solving of this issue.

Thanks.

**Comment by n-ck** [comment] 2015-04-01 01:40
<meta property="og:url" content="<?php $canonical = $this->CanonicalUrl; $cleancanonical = str_replace("http://www.yourdomain.com/http://www.yourdomain.com/", "http://www.yourdomain.com/", $canonical); echo $cleancanonical;?>"/>

This is my temporary solution and works for one of the web stores I'm working on. Put this line in the head.php of your current theme. You will have to remember to delete this line when Lightspeed fixes the issue though. 

Feel free to contact me at my email address in my profile for any questions or more SEO optimization techniques for your Lightspeed Web Store.

**Comment by gabeguz** [comment] 2015-04-02 15:54
@peteles @n-ck That patch will address the issue, yes.  It's not the root cause of the problem, but it will alleviate the symptoms until we release the deeper fix.   We're working on it , and hope to have it fixed in our next release.  No promises, but it's currently in progress.

**Comment by peteles** [comment] 2015-04-04 18:56
It worked. Meanwhile, had to change a litte the code to :  

`<link rel="canonical" href="<?php $canonical = $this->CanonicalUrl; $cleancanonical = str_replace("http://www.site.com/http%3A-wwwsitecom-", "http://www.site.com/", $canonical); echo $cleancanonical;?>"/>`.

Still, links inside the browser bar look awfull.... ;-(

Thanks a lot @n-ck

**Comment by brandinchiu** [comment] 2015-04-04 21:45
If you don't need to reference the URL anywhere else on the page, you can clean it up a bit to take up less space. 

<link rel='canonical' href='<?php echo str_replace("http://www.site.com/http%3A-wwwsitecom-", "http://www.site.com/", $this->CanonicalUrl);

**Comment by ottaz** [comment] 2015-04-15 16:55
This bug has been fixed as of version [3.2.6](https://github.com/lightspeedretail/webstore/tree/3.2.6).

**Closed by ottaz** 2015-04-15 16:55 UTC
Labels: Bug linked to JIRA ticket

**Comment by gabeguz** [comment] 2015-04-16 15:03
In order to fix the product urls, you may need to toggle the "Use Categories In Product Urls in Store Settings > URL Options." to force Web Store to rebuild the product links.
